[package]
name = "nnue_training"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bullet_lib = { git = "https://github.com/jw1912/bullet", package = "bullet_lib" }
